#!/bin/bash
set -eu

jv=$1
IS_LATEST=${2:-}

CIRCLE_BRANCH=${CIRCLE_BRANCH/\//-} # fix/sth => fix-sth
tagName=(${CIRCLE_BRANCH/-/ }) # release-1 => release
SUFFIX="-beta"
if [ $tagName == "release" ]; then
  SUFFIX=""
fi
imageName=$CONTAINER_NAME:v$jv$SUFFIX


echo Building $imageName
docker build --build-arg version=$jv -t $imageName .

VERSION=$(docker run --rm -u 7438:7438 ${imageName}--version | cut -d' ' -f3)
echo "Container reported Julia version: ${VERSION}"

MinorV=$(echo $jv | sed "s/\(.*\)\.\(.*\)\..*/\1.\2/")
MinorV_TAG=$CONTAINER_NAME:v$MinorV$SUFFIX
echo "Tagging as $MinorV_TAG"
docker tag $imageName $MinorV_TAG

# MAJOR_VERSION=(${rv//./ })
# MV_TAG=$CONTAINER_NAME:v$MAJOR_VERSION$SUFFIX
# echo "Tagging as $MV_TAG"
# docker tag $imageName $MV_TAG

if [[ "$tagName" == "release" ]] && [[ "$IS_LATEST" == "true" ]]; then
  echo "Tagging as $CONTAINER_NAME:latest"
  docker tag $imageName $CONTAINER_NAME:latest
fi

