#!/bin/bash
set -eu

jv=$1
imageName=$jv-testing
# ubuntu version
# sudo groupadd -g 7438 sandbox
# alpine version
# addgroup -g 7438 sandbox

# ubuntu version
# sudo adduser --system --no-create-home --shell /bin/false -u 7438 -gid 7438 sandbox
# alpine version
# adduser -S -H -s /bin/false -u 7438 -g sandbox -G sandbox sandbox
# chown -R sandbox:sandbox ${PWD}

echo "Building testing image: $imageName"
docker build -t $imageName -f Dockerfile.testing .

TN="0 2 3"

INIT=$(docker inspect -f '{{index .Config.Labels "io.redsift.sandbox.install" }}' $imageName)
# echo "Calling init = $INIT"
# docker run --rm -u 7438:7438 $imageName $INIT $TN

RUN=$(docker inspect -f '{{index .Config.Labels "io.redsift.sandbox.run" }}' $imageName)
echo "Calling run = $RUN"
echo "$INIT $TN; $RUN $TN" | docker run -i -u 7438:7438 -e DRY=true $imageName
