#!/bin/bash
set -eu

jv=$1
CIRCLE_BRANCH=${CIRCLE_BRANCH/\//-} # fix/sth => fix-sth
tagName=(${CIRCLE_BRANCH/-/ }) # release-1 => release
SUFFIX="-beta"
if [ $tagName == "release" ]; then
  SUFFIX=""
fi
imageName=$CONTAINER_NAME:v$jv$SUFFIX

cat << EOF > ./Dockerfile.testing
FROM ${imageName}
LABEL author="Christos Vontas"
LABEL email="christos@redsift.io"
LABEL version="1.0.1"

COPY --chown=7438:7438 test /run/sandbox/sift

EOF

